version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: "0000"
            MYSQL_DATABASE: "DiarioBienestar"
            MYSQL_USER: "saoma"          # Nombre del usuario
            MYSQL_PASSWORD: "0000"
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
        driver: local 
    